### ISSUE TITLE
Possible feature: Use the Task provider for PDK

### ISSUE THREAD

**Issue by glennsarti** [jpogran/puppet-vscode#151]
Instead of hard-coding commands, we could instead look at using the Task Provider system

https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametaskprovideraspan-classcodeitem-id1155taskproviderspan

https://code.visualstudio.com/docs/editor/tasks#_task-autodetection

This may be useful in the future to parse the output from pdk validate or pdk test and show testing errors.

**Comment by jpogran** [comment]
So, auto tasks need to 'know' about your thing, which won't know PDK out of the box. This means writing them up in package.json, which means commands like `pdk new module foo` won't work as it doesn't accept user input.

Task providers look promising: https://github.com/Microsoft/vscode-extension-samples/blob/master/task-provider-sample/src/extension.ts, however we need to figure out if it'll allow user input, otherwise it's no go as well

**Comment by jpogran** [comment]
Closing this, as the task providers will not work with outside commands
